Repository erc7824/nitrolite, pull requests merged in 2025-06, with the labels that each got.

#162 feat: automated SDK Documentation & Type Generation System
  examples/hello-nitrolite/src/index.ts
  sdk/README.md
  sdk/docs/README.md
  sdk/docs/TYPECHAIN_AUTOMATION.md
  sdk/docs/contracts/consensus.md
  sdk/docs/contracts/counter.md
  sdk/docs/contracts/custody.md
  sdk/docs/contracts/dummy.md
  sdk/docs/contracts/remittanceAdjudicator.md
  sdk/package-lock.json
  sdk/package.json
  sdk/scripts/generate-abi.ts
  sdk/scripts/generate-docs.ts
  sdk/scripts/generate-example-tutorials.ts
  sdk/scripts/setup-hooks.sh
  sdk/scripts/validate-types.ts
  sdk/src/abis/custody/index.ts
  sdk/src/abis/generated.ts
  sdk/src/client/services/Erc20Service.ts
  sdk/src/client/services/NitroliteService.ts
  sdk/src/client/state.ts
  sdk/src/client/types.ts
  sdk/src/utils/channel.ts
  sdk/test/client/index.test.ts
  sdk/test/client/prepare.test.ts
  sdk/test/utils/channel.test.ts
  sdk/tutorials/README.md
Labels: wip, hackathon

#125 ci: enhance Slack notifications with commit message
  .github/workflows/main-pr.yml
  .github/workflows/main-push.yml
  .github/workflows/stable-tag.yml
Labels: wip

#165 feat(snake): use non-zero allocations for players on create_app_session
  .github/workflows/main-push.yml
  examples/snake/client/package-lock.json
  examples/snake/client/package.json
  examples/snake/client/src/App.vue
  examples/snake/client/src/components/GameRoom.vue
  examples/snake/client/src/components/Lobby.vue
  examples/snake/client/src/crypto/index.ts
  examples/snake/client/src/services/ClearNetService.ts
  examples/snake/client/src/services/GameService.ts
  examples/snake/client/src/services/authentication.ts
  examples/snake/server/interfaces/index.ts
  examples/snake/server/middlewares/authMiddleware.ts
  examples/snake/server/package-lock.json
  examples/snake/server/package.json
  examples/snake/server/routes/apiRoutes.ts
  examples/snake/server/server.ts
  examples/snake/server/services/appSessionService.ts
  examples/snake/server/services/brokerService.ts
  examples/snake/server/services/gameService.ts
  examples/snake/server/services/stateService.ts
  examples/snake/server/services/websocketService.ts
Labels: wip

#175 feat(custody): challenge, checkpoint
  contract/src/Custody.sol
  contract/src/Utils.sol
  contract/src/interfaces/IChannel.sol
  contract/test/Custody.t.sol
  contract/test/mocks/FlagAdjudicator.sol
  docs/SECURITY.md
  docs/img/CustodyPDA.png
Labels: documentation, security
