Repository erc7824/nitrolite, pull requests merged in 2025-07, with the labels that each got.

#240 feat(ci): publish SDK automatically
  .github/workflows/main-pr.yml
  .github/workflows/main-push.yml
  .github/workflows/publish-sdk.yml
  .github/workflows/test-forge.yml
  sdk/package.json
Labels: ready

#228 fix(eth_listener): wait for back off timeout in reconcile
  clearnode/eth_listener.go
  clearnode/eth_listener_test.go
Labels: ready

#217 feat(handlers): standardize parameter parsing, add pagination for `public` endpoints
  clearnode/app_session_service.go
  clearnode/channel.go
  clearnode/docs/API.md
  clearnode/list_options.go
  clearnode/rpc_router.go
  clearnode/rpc_router_auth.go
  clearnode/rpc_router_private.go
  clearnode/rpc_router_private_test.go
  clearnode/rpc_router_public.go
  clearnode/rpc_router_public_test.go
  clearnode/rpc_router_test.go
Labels: ready

#246 feat: update app session allocation validations and add tests
  clearnode/app_session_service.go
  clearnode/app_session_service_test.go
Labels: ready

#237 fix(clearnode): uint64 overflow
  clearnode/app_session_service_test.go
  clearnode/channel.go
  clearnode/channel_service.go
  clearnode/channel_service_test.go
  clearnode/config/migrations/postgres/20250704122645_update_channel_amount.sql
  clearnode/custody.go
  clearnode/custody_test.go
  clearnode/docs/API.md
  clearnode/docs/Entities.md
  clearnode/ledger.go
  clearnode/rpc_router.go
  clearnode/rpc_router_callback.go
  clearnode/rpc_router_private.go
  clearnode/rpc_router_private_test.go
  clearnode/rpc_router_public.go
Labels: bug, ready

#235 feat: add reconcile CLI
  clearnode/contract_event.go
  clearnode/custody.go
  clearnode/main.go
  clearnode/reconcile_cli.go
Labels: Ready for Review

#242 feat(sdk): add support for `get_transactions` method
  sdk/.prettierignore
  sdk/src/rpc/api.ts
  sdk/src/rpc/parse/ledger.ts
  sdk/src/rpc/types/index.ts
  sdk/src/rpc/types/request.ts
  sdk/src/rpc/types/response.ts
  sdk/test/unit/rpc/utils.test.ts
Labels: ready

#250 feat(sdk): add support for session data
  integration/common/ws.ts
  integration/package-lock.json
  integration/package.json
  integration/tests/lifecycle.test.ts
  sdk/package-lock.json
  sdk/src/rpc/api.ts
  sdk/src/rpc/parse/app.ts
  sdk/src/rpc/types/request.ts
  sdk/src/rpc/types/response.ts
Labels: ready

#245 fix: do not update ledger on closing a joining channel through challenge
  clearnode/custody.go
  clearnode/custody_test.go
Labels: ready

#256 feat: add wallet tags in returned transactions, update export tool and add tests
  clearnode/docs/API.md
  clearnode/export_transactions_cli.go
  clearnode/export_transactions_cli_test.go
  clearnode/ledger_transaction.go
  clearnode/rpc_router_private.go
  clearnode/rpc_router_private_test.go
  clearnode/rpc_router_public.go
  clearnode/tag.go
  clearnode/tag_test.go
  sdk/package-lock.json
  sdk/src/rpc/parse/ledger.ts
  sdk/src/rpc/types/response.ts
Labels: ready

#262 feat: make user tags case-insensitive
  clearnode/rpc_router_private_test.go
  clearnode/tag.go
Labels: ready

#268 feat: transfer notifications
  clearnode/docs/API.md
  clearnode/rpc_router_callback.go
  clearnode/rpc_router_private.go
Labels: ready

#261 feat: add pagination for get_rpc_history
  clearnode/rpc_router.go
  clearnode/rpc_router_private.go
  clearnode/rpc_router_private_test.go
  clearnode/rpc_store.go
  clearnode/rpc_store_test.go
Labels: ready

#283 refactor(clearnode): migrate `Signature{r,s,v}` to `[]byte`
  clearnode/channel_service.go
  clearnode/custody.go
  clearnode/custody_test.go
  clearnode/nitrolite/bindings.go
  clearnode/nitrolite/signature.go
  clearnode/nitrolite/signature_test.go
  clearnode/rpc_router_private.go
  clearnode/signer.go
  clearnode/testing/client.go
Labels: Ready for Review

#280 refactor rpc handler tests
  clearnode/rpc_router_private_test.go
  clearnode/rpc_router_public_test.go
  clearnode/rpc_router_test.go
Labels: ready

#273 feat: wsNotifier implementation
  clearnode/app_session_service.go
  clearnode/app_session_service_test.go
  clearnode/custody.go
  clearnode/custody_test.go
  clearnode/main.go
  clearnode/notification.go
  clearnode/reconcile_cli.go
  clearnode/rpc_router.go
  clearnode/rpc_router_callback.go
  clearnode/rpc_router_private.go
  clearnode/rpc_router_test.go
Labels: ready

#288 feat: cerebro interface redesign
  examples/cerebro/README.md
  examples/cerebro/auth.go
  examples/cerebro/channel_ops.go
  examples/cerebro/clearnet/auth.go
  examples/cerebro/clearnet/clearnode_client.go
  examples/cerebro/clearnet/events.go
  examples/cerebro/config.go
  examples/cerebro/custody/custody_client.go
  examples/cerebro/custody_ledger.go
  examples/cerebro/list.go
  examples/cerebro/main.go
  examples/cerebro/operator.go
  examples/cerebro/transfer.go
  go.work.sum
Labels: ready

#291 fix: store capruted notifications by userID in tests
  clearnode/app_session_service_test.go
  clearnode/custody_test.go
Labels: ready

#295 feat: replace `stateHash` with `packedState` in message signing
  clearnode/channel_service.go
  clearnode/custody.go
  clearnode/docs/API.md
  clearnode/nitrolite/state.go
  clearnode/rpc_router_private.go
  contract/script/setupChannel.s.sol
  contract/src/Custody.sol
  contract/src/Utils.sol
  contract/test/Custody.t.sol
  contract/test/Custody_integration.t.sol
  contract/test/TestUtils.sol
  contract/test/Utils.t.sol
  contract/test/UtilsHarness.sol
  contract/test/adjudicators/ConsensusTransition.t.sol
  contract/test/adjudicators/Counter.t.sol
  contract/test/adjudicators/SimpleConsensus.t.sol
  examples/cerebro/clearnet/clearnode_client.go
  examples/snake/client/src/services/ClearNetService.ts
  integration/tests/lifecycle.test.ts
  integration/tests/resize_channel.test.ts
  sdk/src/abis/generated.ts
  sdk/src/client/state.ts
  sdk/src/rpc/parse/channel.ts
  sdk/src/rpc/types/index.ts
  sdk/src/rpc/types/response.ts
  sdk/src/utils/state.ts
  sdk/test/unit/client/state.test.ts
  sdk/test/unit/utils/state.test.ts
Labels: multi-component
